### ISSUE TITLE
Indicate forked projects

### ISSUE THREAD

**Issue by humdingerb** [Konrad77/Issues#6]
It'd be useful to make the projects that were created by the user distinguishable from the ones that are merely forked. Maybe even partition the view, with the upper half being the user-created projects, and below the forks.

Double-clicking on a forked project would then open the issues of the original project, as the forked issues are almost always empty.
Or add a context menu to either jump to the forked issues, or original issues.

**Comment by Konrad77** [comment]
Implemented in latest version. No filtering yet though.
